databases:
  - name: devflow-db
    plan: free
    postgresMajorVersion: "16"

services:
  - type: web
    name: devflow-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devflow-db
          property: connectionString
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: JIRA_BASE_URL
        sync: false
      - key: JIRA_EMAIL
        sync: false
      - key: JIRA_API_TOKEN
        sync: false
      - key: JIRA_PROJECT_KEY
        sync: false
      - key: JIRA_WEBHOOK_TOKEN
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_DEFAULT_CHANNEL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: openai/gpt-oss-120b
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
